services:
  clay:
    image: ${IMAGE_NAME:-clay}
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - MALEVICH_CORE_USER=${MALEVICH_CORE_USER}
      - MALEVICH_CORE_ACCESS_KEY=${MALEVICH_CORE_ACCESS_KEY}
    ports:
      - "8000:8000"
